// Board bring-up of the HPM5301EVKLite BSP.
// Sets up the SDK board, then the pins and clocks of every peripheral the application
// uses. The pins come from init_bsp_pins(), and the clocks from the init_*_clock()
// functions; both are generated by the HPM Pinmux Tool from
// boards/hpm5301evklite/tool_config.hpmpc. The LibXR objects for these peripherals are
// created in app_main().
#include <cstdlib>

#include "app_main.h"
#include "board.h"
#include "clock.h"
#include "pinmux.h"

// libstdc++'s default terminate handler links the C++ demangler (about 20 KB of code),
// too much for the 128 KB ILM of the debug-ram preset. LibXR does not use exceptions.
namespace __gnu_cxx
{
void __verbose_terminate_handler() { std::abort(); }
}  // namespace __gnu_cxx

int main(void)
{
  // Clocks, console on UART0 (PA00 TX / PA01 RX), banner
  board_init();

  // Pins: UART0 PA00/PA01, UART3 PB15/PB14, I2C3 PB13/PB12, SPI1 PA26-PA29,
  // GPTMR0 COMP1 PB08, ADC0 IN2 PB10, ACMP COMP1 PB09 / CMP1_INN4 PB11, LED PA10,
  // KEY&BOOT PA03, USB0 PA24/PA25 and PY00 (ID) / PY01 (OC)
  init_bsp_pins();

  // Peripheral clocks
  init_uart3_clock();
  init_i2c3_clock();
  init_spi1_clock();
  init_gptmr0_clock();
  init_adc0_bus_clock();
  init_acmp0_clock();
  init_usb0_clock();

  app_main();
  return 0;
}
